name: Sync Upstream

on:
  schedule:
  - cron:  "*/20 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2

    - name: Sync Repositories
      shell: bash
      run: |
        set -euo pipefail
        export GIT_MERGE_AUTOEDIT=no
        git config --global user.email "theypsilon@gmail.com"
        git config --global user.name "The CI/CD Bot"
        git fetch origin --unshallow
        git remote add upstream https://github.com/MiSTer-devel/<<REPOSITORY>>
        git fetch upstream
        git rebase upstream/master
        git push --force origin master
