name: Full Resync Repositories

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Full Resync Repositories
      run: ./full_resync_repositories.sh
      env:
        REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISPATCH_USER: theypsilon
        DISPATCH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_THEYPSILON }}