name: Sync Repositories

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Sync Repositories
      run: ./sync_repositories.sh
      env:
        REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
