name: Sync Repositories

on:
  schedule:
  - cron:  "*/20 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Sync Repositories
      run: ./sync_repositories.sh
      env:
        REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISPATCH_USER: theypsilon
        DISPATCH_TOKEN: ${{ secrets.REPOSITORY_DISPATCH_THEYPSILON }}
